package com.example.mycontacts.utils

object Constants {
    const val APP_PREFERENCES = "APP_PREFERENCES"
    const val FIRST_LAUNCH_PREF = "FIRST_LAUNCH_PREF"
    const val SHOULD_REQUEST_CALL_PERMISSION_PREF = "CALL_PERM_PREF"
    const val SHOULD_REQUEST_READ_CONTACTS_PERMISSION_PREF = "READ_CONTACTS_PERM_PREF"

    const val CONTACTS_COLUMN_WIDTH = 136F

}